### ISSUE TITLE
procfetch.gif not found in index.html

### ISSUE THREAD

**Issue by akshaykhoje** [TanmayPatil105/procfetch#95]
The procfetch.gif doesn't get displayed at https://tanmaypatil105.github.io/procfetch/index.html.

Fix : We just need to put the procfetch.gif on the new branch. I have fixed it by creating a directory images/ on the gh-pages branch and placing the procfetch.gif in it. Is that the right way or you prefer another way of doing it?

![image](https://user-images.githubusercontent.com/98017423/217716409-1c77be60-622e-4645-a7e1-460df801276d.png)

---
## The fix  

![image](https://user-images.githubusercontent.com/98017423/217716484-e1e08971-0e95-4b9c-8eb0-7535ab5a346c.png)

**Comment by TanmayPatil105** [comment]
The docs are auto generated by Doxygen so everytime there are changes in main branch they will be reflected onto the gh-pages branch using this [workflow](https://github.com/TanmayPatil105/procfetch/blob/main/.github/workflows/doxygen-gh-pages.yml).
### How to create docs?
```
make docs
```
We have used the `img` tag instead of `![]()` to render the gif on the README and Doxygen uses README as the mainpage for the documentation as mentioned in the Doxyfile:
```
USE_MDFILE_AS_MAINPAGE = README.md
```

`![]()` can be used but we cannot set the size of width and height of gif using it.

**Comment by TanmayPatil105** [comment]
Checkout #96 !!

**Comment by TanmayPatil105** [comment]
Closing as #96 and this [commit](https://github.com/TanmayPatil105/doxygen-github-pages-action/tree/055b74374487831dc5a86cf5a555cb570cddae88) fixed it.
